# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R


# safe list
branches:
  only:
  - master
  - develop



# NOTES:
# Not doing devel on osx because CRAN doesn’t publish OSX binary packages for r-devel.
# Including `r_binary_packages` in oldrel caused "number of columns of matrices must
#     match" error



matrix:
  include:
  - r: devel
    os: linux
    cache: packages
  - r: release
    os: linux
    cache: packages
    env:
      - PKG_TARBALL=armmr_0.0.0.9000.tar.gz
    r_packages:
      - covr
      - pkgdown
    after_success:
      - Rscript -e 'library(covr); codecov()'
      - tar -C .. -xf $PKG_TARBALL
      - rm -rf jackalope.Rcheck
      - Rscript -e 'pkgdown::build_site()'
    deploy:
      - provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: false
        local-dir: docs
        on:
          branch: master
  - r: release
    os: osx
    cache: packages
    r_binary_packages:
      - Rcpp
      - RcppArmadillo
      - knitr
  - r: oldrel
    os: linux
  - r: oldrel
    os: osx
